# Generated by Django 3.2.25 on 2026-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0029_proposal_queue_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='percent_for_quorum',
            field=models.PositiveSmallIntegerField(blank=True, default=20),
        ),
    ]
